name: Terraform Deployment

on:
  workflow_dispatch:  # Manually trigger workflow

jobs:
  terraform:
    runs-on: ubuntu-latest  # You can choose your preferred OS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Adjust to your Terraform version

      # Authenticate with GCP using service account key
      - name: Configure GCP credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Ensure GCP_SA_KEY secret is added in repository settings

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan Terraform changes
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Apply Terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        # You might want to add -auto-approve for non-interactive runs.
